import { useState, useEffect } from 'react';
import { Hash, FileText, RefreshCw, AlertCircle, X } from 'lucide-react';

// ─── Types ────────────────────────────────────────────────────────────────────

type ContentFormat = 'long-form' | 'short-form';

export interface TopicTitleFieldsProps {
  format: ContentFormat;
  topic: string;
  title?: string;
  onTopicChange: (topic: string) => void;
  onTitleChange?: (title: string) => void;
  onRegenerateRequest?: () => void;
  autoGeneratedTopic?: string;
}

// ─── Topic Change Notification ────────────────────────────────────────────────

interface TopicChangeNotificationProps {
  show: boolean;
  onRegenerate: () => void;
  onDismiss: () => void;
}

function TopicChangeNotification({ show, onRegenerate, onDismiss }: TopicChangeNotificationProps) {
  if (!show) return null;

  return (
    <div className="bg-yellow-500/10 border border-yellow-500/20 rounded-lg p-3 flex items-start gap-3 animate-in fade-in slide-in-from-top-2 duration-200">
      <AlertCircle className="w-5 h-5 text-yellow-500 flex-shrink-0 mt-0.5" />
      <div className="flex-1 min-w-0">
        <p className="text-sm font-medium text-foreground mb-1">
          Topic updated
        </p>
        <p className="text-xs text-muted-foreground">
          Regenerate content to apply changes to this item
        </p>
      </div>
      <div className="flex items-center gap-2 flex-shrink-0">
        <button
          onClick={onRegenerate}
          className="flex items-center gap-1.5 px-3 py-1.5 bg-yellow-500/20 hover:bg-yellow-500/30 text-yellow-400 rounded-md transition-colors text-xs font-medium"
        >
          <RefreshCw className="w-3 h-3" />
          Regenerate
        </button>
        <button
          onClick={onDismiss}
          className="p-1 hover:bg-secondary rounded transition-colors"
        >
          <X className="w-4 h-4 text-muted-foreground" />
        </button>
      </div>
    </div>
  );
}

// ─── Main Component ───────────────────────────────────────────────────────────

export function TopicTitleFields({
  format,
  topic,
  title,
  onTopicChange,
  onTitleChange,
  onRegenerateRequest,
  autoGeneratedTopic,
}: TopicTitleFieldsProps) {
  const [localTopic, setLocalTopic] = useState(topic);
  const [localTitle, setLocalTitle] = useState(title || '');
  const [showNotification, setShowNotification] = useState(false);
  const [hasTopicChanged, setHasTopicChanged] = useState(false);

  // Track if topic has been manually changed
  useEffect(() => {
    if (localTopic !== topic) {
      setLocalTopic(topic);
      setHasTopicChanged(false);
      setShowNotification(false);
    }
  }, [topic]);

  useEffect(() => {
    if (title !== undefined && localTitle !== title) {
      setLocalTitle(title);
    }
  }, [title]);

  const handleTopicChange = (newTopic: string) => {
    setLocalTopic(newTopic);
    onTopicChange(newTopic);

    // Show notification if topic was changed from auto-generated value
    if (autoGeneratedTopic && newTopic !== autoGeneratedTopic && newTopic !== topic) {
      setHasTopicChanged(true);
      setShowNotification(true);
    }
  };

  const handleTopicBlur = () => {
    // Final validation on blur if needed
    if (localTopic.trim() === '') {
      setLocalTopic(topic);
    }
  };

  const handleTitleChange = (newTitle: string) => {
    setLocalTitle(newTitle);
    if (onTitleChange) {
      onTitleChange(newTitle);
    }
  };

  const handleRegenerate = () => {
    setShowNotification(false);
    setHasTopicChanged(false);
    if (onRegenerateRequest) {
      onRegenerateRequest();
    }
  };

  const handleDismissNotification = () => {
    setShowNotification(false);
  };

  return (
    <div className="space-y-4">
      {/* Topic Change Notification */}
      <TopicChangeNotification
        show={showNotification}
        onRegenerate={handleRegenerate}
        onDismiss={handleDismissNotification}
      />

      {/* Topic Field - Always shown */}
      <div>
        <label className="flex items-center gap-2 text-sm font-medium text-foreground mb-2">
          <Hash className="w-4 h-4 text-primary" />
          Topic
        </label>
        <input
          type="text"
          value={localTopic}
          onChange={(e) => handleTopicChange(e.target.value)}
          onBlur={handleTopicBlur}
          placeholder="e.g., Breathing Techniques for Work Stress"
          className="w-full px-4 py-3 bg-input-background border border-border rounded-lg text-foreground placeholder:text-muted-foreground"
        />
        <p className="text-xs text-muted-foreground mt-1.5">
          {autoGeneratedTopic ? (
            <span className="flex items-center gap-1">
              <span className="w-1 h-1 rounded-full bg-primary" />
              Auto-generated and fully editable
            </span>
          ) : (
            'Specific subject for this content item'
          )}
        </p>
      </div>

      {/* Title Field - Only for long-form content */}
      {format === 'long-form' && onTitleChange && (
        <div>
          <label className="flex items-center gap-2 text-sm font-medium text-foreground mb-2">
            <FileText className="w-4 h-4 text-primary" />
            Title
          </label>
          <input
            type="text"
            value={localTitle}
            onChange={(e) => handleTitleChange(e.target.value)}
            placeholder="e.g., 5 Simple Breathing Exercises to Reduce Workplace Anxiety"
            className="w-full px-4 py-3 bg-input-background border border-border rounded-lg text-foreground placeholder:text-muted-foreground"
          />
          <p className="text-xs text-muted-foreground mt-1.5">
            The specific headline for this article or post
          </p>
        </div>
      )}

      {/* Format-specific help text */}
      {format === 'short-form' && (
        <div className="pt-2 border-t border-border">
          <p className="text-xs text-muted-foreground">
            Short-form content uses the topic as the primary identifier. No separate title needed.
          </p>
        </div>
      )}
    </div>
  );
}

// ─── Example Usage Component ──────────────────────────────────────────────────

export function TopicTitleFieldsDemo() {
  // Long-form example
  const [longFormTopic, setLongFormTopic] = useState('Breathing Techniques for Work Stress');
  const [longFormTitle, setLongFormTitle] = useState('5 Simple Breathing Exercises to Reduce Workplace Anxiety');

  // Short-form example
  const [shortFormTopic, setShortFormTopic] = useState('Quick Desk Meditation');

  const handleRegenerate = () => {
    console.log('Regenerating content...');
    alert('Content regeneration started!');
  };

  return (
    <div className="flex-1 overflow-y-auto p-6 bg-background">
      <div className="max-w-5xl mx-auto">
        <h1 className="text-2xl font-bold text-foreground mb-2">Topic & Title Fields Demo</h1>
        <p className="text-sm text-muted-foreground mb-8">
          Demonstrating topic and title fields for different content formats
        </p>

        <div className="grid grid-cols-2 gap-6">
          {/* Long-form Example */}
          <div className="bg-card border border-border rounded-xl p-6">
            <div className="flex items-center gap-2 mb-4">
              <FileText className="w-5 h-5 text-primary" />
              <h2 className="text-base font-semibold text-foreground">Long-Form Content</h2>
            </div>
            <p className="text-xs text-muted-foreground mb-4">
              Shows both Topic and Title fields
            </p>
            <TopicTitleFields
              format="long-form"
              topic={longFormTopic}
              title={longFormTitle}
              onTopicChange={setLongFormTopic}
              onTitleChange={setLongFormTitle}
              onRegenerateRequest={handleRegenerate}
              autoGeneratedTopic="Breathing Techniques for Work Stress"
            />
          </div>

          {/* Short-form Example */}
          <div className="bg-card border border-border rounded-xl p-6">
            <div className="flex items-center gap-2 mb-4">
              <Hash className="w-5 h-5 text-primary" />
              <h2 className="text-base font-semibold text-foreground">Short-Form Content</h2>
            </div>
            <p className="text-xs text-muted-foreground mb-4">
              Shows only Topic field (no title)
            </p>
            <TopicTitleFields
              format="short-form"
              topic={shortFormTopic}
              onTopicChange={setShortFormTopic}
              onRegenerateRequest={handleRegenerate}
              autoGeneratedTopic="Quick Desk Meditation"
            />
          </div>
        </div>

        {/* Current State */}
        <div className="mt-8 bg-secondary/30 border border-border rounded-xl p-6">
          <h3 className="text-sm font-semibold text-foreground mb-4">Current State</h3>
          <div className="grid grid-cols-2 gap-6 text-xs font-mono">
            <div>
              <p className="text-muted-foreground mb-2">Long-form:</p>
              <pre className="text-foreground whitespace-pre-wrap">
                {JSON.stringify({ topic: longFormTopic, title: longFormTitle }, null, 2)}
              </pre>
            </div>
            <div>
              <p className="text-muted-foreground mb-2">Short-form:</p>
              <pre className="text-foreground whitespace-pre-wrap">
                {JSON.stringify({ topic: shortFormTopic }, null, 2)}
              </pre>
            </div>
          </div>
        </div>

        {/* Usage Notes */}
        <div className="mt-8 bg-blue-500/10 border border-blue-500/20 rounded-xl p-6">
          <h3 className="text-sm font-semibold text-foreground mb-3">How It Works</h3>
          <div className="space-y-2 text-sm text-muted-foreground">
            <p>
              • <span className="text-foreground font-medium">Long-form content</span> (blog posts, articles): Shows both Topic and Title fields
            </p>
            <p>
              • <span className="text-foreground font-medium">Short-form content</span> (social posts, tweets): Shows only Topic field
            </p>
            <p>
              • <span className="text-foreground font-medium">Topic changes</span>: When you edit the topic, a notification appears prompting you to regenerate the content
            </p>
            <p>
              • <span className="text-foreground font-medium">Auto-generated</span>: Topics are auto-generated but fully editable
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
